### ISSUE TITLE
No roadmap info

### ISSUE THREAD

**Issue by igor-panassiouk** [clueware/redmine_my_roadmaps#25]
Log entries after visiting "My roadmaps" page:

Started GET "/my_roadmaps" for 192.168.20.33 at 2015-08-19 01:14:41 +0300
Processing by MyRoadmapsController#index as HTML
  Current user: Panassiouk (id=15)
  Rendered queries/_filters.html.erb (24.1ms)
  Rendered plugins/redmine_my_roadmaps/app/views/my_roadmaps/_filters.html.erb (26.7ms)
  Rendered plugins/redmine_my_roadmaps/app/views/my_roadmaps/index.html.erb within layouts/base (28.2ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.9ms)
  Rendered plugins/redmine_allocation/app/views/hooks/allocation/_view_layouts_base_html_head.html.erb (0.1ms)
  Rendered inline template (0.9ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.2ms)
  Rendered plugins/rm_user_mentions/app/views/hooks/rum/_head.html.erb (1.0ms)
  Rendered plugins/timelog_timer/app/views/timelog/_timer.html.erb (1.2ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_add_css.html.erb (0.5ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.3ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.2ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.8ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.5ms)

**Comment by clueware** [comment]
Could you please post the information page from the Administration menu please? If you have other plugins installed, it could also help havi'g a list of them.

Thanks

**Comment by igor-panassiouk** [comment]
Environment:
  Redmine version                2.6.6.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.10.4
  Filesystem  
Redmine plugins:
  a_common_libs                  1.1.5
  ajax_counters                  0.0.1
  clipboard_image_paste          1.8
  custom_menu                    1.5.0
  issue_id                       0.0.1b
  localizable                    0.3.0
  meetings                       0.0.2
  progressive_gantt_mods         0.0.2
  progressive_projects_list      2.0.1
  project_overview               1.2.0
  redmine_add_to_calendar        0.0.2
  redmine_agile                  1.3.5
  redmine_allocation             1.1.2
  redmine_app__space             1.0.1
  redmine_app_timesheets         1.3.16
  redmine_banner                 0.1.1
  redmine_base_deface            0.0.1
  redmine_base_select2           0.0.1
  redmine_better_gantt_chart     0.9.0
  redmine_changeauthor           1.0.1
  redmine_charts2                0.2.1
  redmine_checklists             3.1.1
  redmine_ckeditor               1.0.16
  redmine_contacts               4.0.1
  redmine_dashboard              2.2.2
  redmine_documents              1.0.0
  redmine_finance                2.0.0
  redmine_image_clipboard_paste  1.0.0
  redmine_information            1.0.2
  redmine_issue_tabs             1.1.0
  redmine_issuelimits            0.0.3
  redmine_knowledgebase          3.0.4
  redmine_login_audit            0.1.5
  redmine_monitoring_controlling 0.1.1
  redmine_multiprojects_issue    0.2
  redmine_people                 0.1.8
  redmine_per_project_formatting 0.0.3
  redmine_percent_done_configuration 0.1.23x
  redmine_plugin_views_revisions 0.0.1
  redmine_pretend                0.0.3
  redmine_reminder               0.3.1
  redmine_send_mails             0.3.23xBeta
  redmine_spent_time_required    0.0.1
  redmine_stats                  0.0.3
  redmine_sticky_messages        1.0.1
  redmine_summed_fields          1.0.0
  redmine_update_reminder        1.0.1
  redmine_watcher_groups         1.0.1
  redmine_work_time              0.3.0
  redmine_workflow_enhancements  0.4.0
  redmine_workload               1.0.2
  redmine_xls_export             0.2.1.t8
  rm_user_mentions               1.0.0
  sidebar_hide                   0.0.7
  timelog_timer                  2.0.0
  unread_issues                  1.5.0
  wiking                         1.0.0b

**Comment by clueware** [comment]
I failed to reproduce the issue on a fresh redmine install with the same configuration, it may be an interaction with one of the other plugins. I'll try to find which one, if you can do some testing on your side it would be great though. Thanks!
