### ISSUE TITLE
Which version/branch to use with Redmine 3.3

### ISSUE THREAD

**Issue by acosonic** [clueware/redmine_my_roadmaps#27]
Thanks

**Comment by clueware** [comment]
Redmine 3.0 changed a few things and as we've move from Redmine to Jira at work, I've not found the time to investigate further.
<del>I'll try to find some time to look into porting the plugin to the 3.x Redmine release.</del>

edit: forgot I already ported it to 3.0. 😄

**Comment by clueware** [comment]
Just tried 3.3, and things moved a bit since 3.0. Rendering the whole roadmaps with no filters works, but as soon as you add a filter it breaks in various, interesting ways.

**Comment by acosonic** [comment]
Thanks. Btw, why did you move to Jira in favor of Redmine?

**Comment by clueware** [comment]
The move to Jira was motivated by - at last - embracing Agility. We tries a few Redmine plugins but none were convincing, so we opted for the solution our agilist had the most experience with. The final selling point was the integration with Service Desk and Confluence, though.

P.S.: I have a personal preference for Taiga (https://taiga.io/) which seems more streamlined that Jira for small, personal projects. One of the selling points of Jira Software is that you can have, in the same instance, Agile and legacy projects, with the ability to link issues/user stories between them. It thus may be more relevant to a significantly large project/company.

**Comment by clueware** [comment]
I'm working on a fix to have the plugin behave when used with 3.x, and there was a serious issue with the 0.2.1 release: the "tracker" filter does not work at all as expected when an "is not" filter is used.
The error is entirely due to my ignorance of Rails 4 changes, fortunately the fix is quite straightforward.
I'll make sure it work on the whole 3.x minor versions and I'll push a 0.2.2 release

**Comment by clueware** [comment]
Should be fixed by the 0.2.2_redmine3.0 release, if you can please check it out?

**Comment by acosonic** [comment]
Looks and works fine on 3.3.1

**Comment by acosonic** [comment]
What  I did was

`git clone -b Redmine_3.0 https://github.com/clueware/redmine_my_roadmaps.git
`
And restarted Redmine after that

**Comment by clueware** [comment]
Indeed, it's the Redmine_3.0 branch that carries the fix.

**Comment by acosonic** [comment]
Thanks!
